genome = "ATAGTTGGATTGGACATCTTGGCTCAAGGTTCGCGTAATGTTTAGTAGAGCGGGGAACTAAAGCCCCGGTATGCGCCTGTTTAGCTTCCCATGATATGATTGCTACGCGACATTAGATGTCGACTAGGGATACTGCATACAACTCTCCGAGCCCTATCACGGTGTGGGCTCTAATCGATTTTGGAAGGATCACAAGGCAGAATAAGGGGGTAGTTCCACCGCACGTTATCGGGCCAGTCGAAGCCACGTTGTCGGCACGCTTCGGCACAAAGGCAAAGTTAGGCTAGAGTCTCCGGCGCACGCGACTCTGCGTAGTGTTAAGAGCTAAGTTGATCGGATTCTGAACCATACGATATCTTTTTAGGGAGCATGGTAGTGGTGTAGCCGGATGATCAGGCTTGCGTGACTCAACCCCCACTCACAGCAGAGCTCTGGAGGCTACTGCCACCCTGTGAGCCCGCGTAGAAGGAGTTGAACATACACCCTATGGCAGATCCACGGTATCGTATGAGCACAAGGTTGATTCATTCGCGGGGCAGTAGCCTATCCTAGAAATAAGAAAGACTTCTTAAACCGCGGGGTGCTAAGTGCAGGATAATTATTCATCGGGCTTCATTGTGAAGGTGGGGACGACTGCCGTGATCGCGGAATCGGTCGGCTCGGTCAATTGGAACAGCAGGTGTAAAGTTTCTCTCATCGCGTCTGACCTTAGCGGGTGGTAGCTGAGCCTGATCTGGGCACACGCGGACTTCATGTAGGTCACAGTACCGATTGTGCCTTTAGGCGAATTCGCCCGAAACAATCTATATCCGGCAATTCACGGTGGTTGCATGACCTTATTAGTCTTAGAGAGGACTGGATC"
def countNucleotides(text: str) -> dict[str, int]:
    counts = {
        "A":0,
        "C":0,
        "G": 0,
        "T": 0
    }

    x = 0

    while (x < len(text)):

        if text[x:x+1]=="A":
            currentNum = counts.get("A")
            counts.update({"A": currentNum+1})
        elif text[x:x+1]=="C":
            currentNum = counts.get("C")
            counts.update({"C": currentNum+1})
        elif text[x:x+1]=="G":
            currentNum = counts.get("G")
            counts.update({"G": currentNum+1})
        elif text[x:x+1]=="T":
            currentNum = counts.get("T")
            counts.update({"T": currentNum+1})
        x=x+1

    answer = ""
    for value in counts.values():
        answer = answer + str(value) + " "

    return answer.strip()

# keys = countNucleotides(genome).values();

# print(keys)