from .pattern_count import PatternCount

t = "CACTAAGCGCCACCGGCACTAAGCGTAAAAACACGTCAGGTGTCACTAAGCGCCACCGGCACTAAGCGTAAAAACACGTCAGGTGTCCACCGGCCACCGGCACTAAGCGGTCAGGTGTTAAAAACACCCACCGGGTCTCCTCCACTAAGCGTAAAAACACCCACCGGCCACCGGCCACCGGGTCAGGTGTCCACCGGCCACCGGTAAAAACACGTCTCCTCTAAAAACACGTCTCCTCGTCAGGTGTGTCTCCTCCACTAAGCGGTCAGGTGTTAAAAACACGTCTCCTCCCACCGGCCACCGGCACTAAGCGTAAAAACACCCACCGGCCACCGGCCACCGGGTCTCCTCGTCTCCTCCCACCGGGTCTCCTCCACTAAGCGCCACCGGTAAAAACACGTCAGGTGTGTCAGGTGTTAAAAACACCCACCGGTAAAAACACGTCTCCTCCACTAAGCGCACTAAGCGGTCAGGTGTCACTAAGCGGTCTCCTCGTCAGGTGTCCACCGGGTCTCCTCCCACCGGGTCAGGTGTTAAAAACACCCACCGGCCACCGGCACTAAGCGGTCTCCTCCACTAAGCGCCACCGGCCACCGGTAAAAACACGTCAGGTGTGTCAGGTGTTAAAAACACGTCTCCTCCCACCGGCACTAAGCGGTCAGGTGTTAAAAACACGTCAGGTGTCCACCGGCCACCGGTAAAAACACCCACCGGTAAAAACACGTCTCCTCTAAAAACACCCACCGGTAAAAACACTAAAAACACCACTAAGCGGTCTCCTCGTCTCCTCTAAAAACACCACTAAGCGCCACCGGCACTAAGCGTAAAAACAC"
l = 13

def FrequentWords(text: str, k: int) -> set[str]:

    frequentPatterns = set()
    counts= []
    i = 0
    while i < len(text)-k:
        pattern = text[i:i+k]
        counts.append(PatternCount(text, pattern))
        i = i+1
    
    maxCount = max(counts)

    i = 0
    while i < len(text)-k:
        if(counts[i]== maxCount):
            frequentPatterns.add(text[i:i+k])
        i = i+1
    
    return frequentPatterns

print(FrequentWords(t, l))