t = "CATTAACAGCCATAACAGCTTAGTAACAGCGATAACAGCTTAACAGCTAACAGCTTTTTAACAGCGCTAGATAGTCATAACAGCTAACAGCTAACAGCTAACAGCCTAACAGCTAACAGCCCGCAGCCTTAACAGCCTAACAGCGTAACAGCATTCGTAACAGCCCTAACAGCTAACAGCTCGGATAACAGCGGTAACAGCTGTTATCGCTGTTAACAGCTCTATTAATAACAGCTAACAGCTATAACAGCCGCCTAACAGCTAACAGCTAACAGCATAACAGCATGTCTCTAACAGCATAACAGCACTGTAACAGCTAACAGCACCCATAACAGCCTAGGAAAAATAACAGCCTAACAGCGCGACTATAACAGCTTATTCTAACAGCTAACAGCTAACAGCCCGGTAACAGCTGCTAACAGCTAACAGCTAACAGCTAACAGCGGAGCGATTAACAGCCTAACAGCATTAACAGCGTAACAGCTAACAGCTAACAGCCTCTAACAGCGGTAACAGCGCGTAACAGCGCGAAGTAACAGCCTAACAGCTAACAGCTAACAGCTATAACAGCCGAGTAACAGCTAACAGCCGTTAACAGCAGTAACAGCAACCTAACAGCGATAACAGCTAACAGCCGATGTAACAGCTTAACAGCCTAACAGCAATATAACAGCCATAACAGCGATTAACAGCTAACAGCTCCTAACAGCATTAACAGCGGTGAGATAACAGCCACCATGCTTACTAACAGCGGTAACAGCGTAACAGCTTTAACAGCTCGGCGCTTAACAGCTCAGCTACAAGCTAACAGCTTAACAGCATAACAGCCGGTAACAGCACTCTAACAGCGTAACAGCCTAACAGCGCGAGACCGCTGTAACAGCTTAACAGCTAACAGCTAACAGCATCTAACAGCACCTAGTTACCTAACAGCATGTACTAACAGCCCCCTCAGAATTAACAGCTAACAGCGTAACAGCAGGTGCAGTTTTAACAGC" \

p = "TAACAGCTA"
def PatternCount(text: str, pattern: str) -> int:
    count = 0
    x = 0
    while x < (len(text)-len(pattern))+1:
        if(text[x:x+len(pattern)]) == pattern:
            count = count+1
        x = x+1
    return count

print(PatternCount(t, p))
