"""Count occurrences of a pattern in text."""
t = "CATTAACAGCCATAACAGCTTAGTAACAGCGATAACAGCTTAACAGCTAACAGCTTTTTAACAGCGCTAGATAGTCATAACAGCTAACAGCTAACAGCTAACAGCCTAACAGCTAACAGCCCGCAGCCTTAACAGCCTAACAGCGTAACAGCATTCGTAACAGCCCTAACAGCTAACAGCTCGGATAACAGCGGTAACAGCTGTTATCGCTGTTAACAGCTCTATTAATAACAGCTAACAGCTATAACAGCCGCCTAACAGCTAACAGCTAACAGCATAACAGCATGTCTCTAACAGCATAACAGCACTGTAACAGCTAACAGCACCCATAACAGCCTAGGAAAAATAACAGCCTAACAGCGCGACTATAACAGCTTATTCTAACAGCTAACAGCTAACAGCCCGGTAACAGCTGCTAACAGCTAACAGCTAACAGCTAACAGCGGAGCGATTAACAGCCTAACAGCATTAACAGCGTAACAGCTAACAGCTAACAGCCTCTAACAGCGGTAACAGCGCGTAACAGCGCGAAGTAACAGCCTAACAGCTAACAGCTAACAGCTATAACAGCCGAGTAACAGCTAACAGCCGTTAACAGCAGTAACAGCAACCTAACAGCGATAACAGCTAACAGCCGATGTAACAGCTTAACAGCCTAACAGCAATATAACAGCCATAACAGCGATTAACAGCTAACAGCTCCTAACAGCATTAACAGCGGTGAGATAACAGCCACCATGCTTACTAACAGCGGTAACAGCGTAACAGCTTTAACAGCTCGGCGCTTAACAGCTCAGCTACAAGCTAACAGCTTAACAGCATAACAGCCGGTAACAGCACTCTAACAGCGTAACAGCCTAACAGCGCGAGACCGCTGTAACAGCTTAACAGCTAACAGCTAACAGCATCTAACAGCACCTAGTTACCTAACAGCATGTACTAACAGCCCCCTCAGAATTAACAGCTAACAGCGTAACAGCAGGTGCAGTTTTAACAGC" \

p = "TAACAGCTA"

def PatternCount(text: str, pattern: str) -> int:
    count = 0
    x = 0
    while x < (len(text)-len(pattern))+1:
        if(text[x:x+len(pattern)]) == pattern:
            count = count+1
        x = x+1
    return count
    

    """Return the number of occurrences of pattern in text.

    Matches are case-sensitive and may overlap. Assume pattern is nonempty.
    Return 0 if pattern is longer than text or text is empty.

    Example:
        PatternCount("AAAA", "AA") returns 3.
    """
    # TODO: Implement this function.
    raise NotImplementedError("Implement PatternCount")
print(PatternCount(t, p))